language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.3.3
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: CODE_COVERAGE=1
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI

install: wget -qO - https://github.com/Slamdunk/travis-scripts/raw/master/php-install.sh | sh

script: wget -qO - https://github.com/Slamdunk/travis-scripts/raw/master/php-script.sh | sh

notifications:
  email: false
